In [ ]:
# Imort necessary libraries
import pandas as pd

# Reading in the data
bills_actions = pd.read_csv("C:\\Users\\jland\\OneDrive\\Emory Essentials\\CLASSES Fall 2025\\Computing\\datasci530fall2025\\Lecture 10\\data_raw\\bills_actions.csv")
bills_actions.dtypes
bills_actions.duplicated().sum()  

# there are 3,303 rows and 7 columns, 49 of these rows are duplicates

bills_actions['bill_number'].is_unique # not an individual identifier
bills_actions['member_id'].is_unique # also not a unique identifier

np.int64(49)

In [ ]:
# Checking for potential unique identifiers

candidates = [
    ["bill_number", "bill_type", "action"],
    ["bill_number", "bill_type", "member_id", "action"],
    ["bill_number", "bill_type", "main_action", "member_id"],
    ["bill_number", "bill_type", "main_action", "action"],
]

for cols in candidates:
    dups = bills_actions.duplicated(subset=cols).sum()
    print(cols, "duplicates:", dups, "→ unique?" , dups == 0)

In [ ]:
## After looking through the data, I don't see a reason to keep the duplicates, so I will remove them.
# counts how many times each combination of all columns occurs
bills_actions["dups"] = bills_actions.duplicated(keep=False)  # True/False if row appears >1

bills_actions = bills_actions[bills_actions["dups"] == 0]

bills_actions.duplicated().sum()   ## now we have no duplicates
bills_actions.dtypes

np.int64(0)

In [23]:
for col in bills_actions.columns:
    print(col, bills_actions[col].nunique())
bills_actions 
    ## 
    ## There are no unique identifiers in this dataset
    ## There 1,331 unique bill numbers, 8 different bill types, 9 different categories

Congress 1
bill_number 1331
bill_type 8
action 2404
main_action 13
category 9
member_id 381
dups 1

,Congress,bill_number,bill_type,action,main_action,category,member_id,dups
0,116,1029,s,S.Amdt.1274 Amendment SA 1274 proposed by Sena...,senate amendment proposed (on the floor),amendment,858,False
1,116,1031,s,S.Amdt.2698 Amendment SA 2698 proposed by Sena...,senate amendment proposed (on the floor),amendment,675,False
2,116,1160,s,S.Amdt.2659 Amendment SA 2659 proposed by Sena...,senate amendment proposed (on the floor),amendment,858,False
3,116,1199,s,"Committee on Health, Education, Labor, and Pen...",senate committee/subcommittee actions,senate bill,1561,False
4,116,1208,s,Committee on the Judiciary. Reported by Senato...,senate committee/subcommittee actions,senate bill,1580,False
...,...,...,...,...,...,...,...,...
3298,116,9,hr,H.Amdt.172 Amendment (A004) offered by Ms. Kus...,house amendment offered,amendment,36,False
3299,116,9,hr,H.Amdt.171 Amendment (A003) offered by Ms. Hou...,house amendment offered,amendment,186,False
3300,116,9,hr,H.Amdt.170 Amendment (A002) offered by Ms. Oma...,house amendment offered,amendment,477,False
3301,116,9,hr,POSTPONED PROCEEDINGS - At the conclusion of d...,other house amendment actions,amendment,393,False
3302,116,9,hr,H.Amdt.169 Amendment (A001) offered by Mr. Esp...,house amendment offered,amendment,6,False

In [ ]:
category_pct = bills_actions.groupby("category").size()
category_pct = category_pct / category_pct.sum()
category_pct = category_pct.sort_values(ascending=False)
print(category_pct)

# 45.6% of the bills are ammendemnts
# 27% are house bills
# ~16% are senate bills
 # ~7.3% are house resolutions
 # Less than 2% are senate resolutions
# House and senate joint/concurrent resoluations each make up less than 1% of the data.

category
amendment                       0.456157
house bill                      0.272699
senate bill                     0.159826
house resolution                0.072761
senate resolution               0.018657
house joint resolution          0.006841
house concurrent resolution     0.006219
senate concurrent resolution    0.004353
senate joint resolution         0.002488
dtype: float64

In [26]:
bills_actions
main_action_pct = bills_actions.groupby("main_action").size()
main_action_pct = main_action_pct / main_action_pct.sum()
main_action_pct = main_action_pct.sort_values(ascending=False)
print(main_action_pct)
bills_actions
# House floor actions comprise almost 32% of all bills
# House amendment offeres comprise just more than 1/4 of all bills
# Senate committee and subcommittee actions comprise 13% of the bills
# Other House amendment actions comprise 10% of the bills
# Senate amendmnents proposed on the floor comprise nearly 9% of the bills in the dataset.
# House Committee/Subcommittee actions comprise 6.1% of the bills
# "Reported to senate" makes up 1% of the bills
# Every other type comprises less than 1% of the bills

main_action
house floor actions                              0.315609
house amendment offered                          0.257463
senate committee/subcommittee actions            0.134950
other house amendment actions                    0.104167
senate amendment proposed (on the floor)         0.088930
house committee/subcommittee actions             0.061567
reported to senate                               0.011194
senate committee report filed after reporting    0.010261
other senate amendment actions                   0.005597
resolving differences -- house actions           0.004353
senate floor actions                             0.004042
house discharge petition filed                   0.000933
resolving differences -- senate actions          0.000933
dtype: float64

,Congress,bill_number,bill_type,action,main_action,category,member_id,dups
0,116,1029,s,S.Amdt.1274 Amendment SA 1274 proposed by Sena...,senate amendment proposed (on the floor),amendment,858,False
1,116,1031,s,S.Amdt.2698 Amendment SA 2698 proposed by Sena...,senate amendment proposed (on the floor),amendment,675,False
2,116,1160,s,S.Amdt.2659 Amendment SA 2659 proposed by Sena...,senate amendment proposed (on the floor),amendment,858,False
3,116,1199,s,"Committee on Health, Education, Labor, and Pen...",senate committee/subcommittee actions,senate bill,1561,False
4,116,1208,s,Committee on the Judiciary. Reported by Senato...,senate committee/subcommittee actions,senate bill,1580,False
...,...,...,...,...,...,...,...,...
3298,116,9,hr,H.Amdt.172 Amendment (A004) offered by Ms. Kus...,house amendment offered,amendment,36,False
3299,116,9,hr,H.Amdt.171 Amendment (A003) offered by Ms. Hou...,house amendment offered,amendment,186,False
3300,116,9,hr,H.Amdt.170 Amendment (A002) offered by Ms. Oma...,house amendment offered,amendment,477,False
3301,116,9,hr,POSTPONED PROCEEDINGS - At the conclusion of d...,other house amendment actions,amendment,393,False
3302,116,9,hr,H.Amdt.169 Amendment (A001) offered by Mr. Esp...,house amendment offered,amendment,6,False

In [ ]:
## Count the number of "house floor actions" in main_action
house_floor_actions = bills_actions.query("main_action == 'house floor actions'")
house_floor_actions
print(house_floor_actions.shape)  

##There 1,015 house floor actions in the dataset

(1015, 8)

In [ ]:
## Of the house floor actions, how many of them contain the word "suspends"?
suspended = house_floor_actions["action"].str.contains("suspend", case=False, na=False)
print(suspended.sum())       # <-- number of rows containing "suspend"

amended = house_floor_actions["action"].str.contains("amended", case=False, na=False)
print(amended.sum())         # <-- number of rows containing "amended"

# 730 house floor actions contain the word "suspend"
# 430 house floor actions contain the word "amended"

730
430

In [ ]:
mask = house_floor_actions["action"].str.contains(
    r"(?=.*suspend)(?=.*amend)",  # lookahead for both words
    case=False,
    na=False,
    regex=True
)

house_floor_actions[mask]       # shows rows with BOTH words
mask.sum()                      # count how many


# This confirms that all 430 rows that contain "amended" also contain "suspend"

np.int64(430)

In [46]:
pattern = r"(?i)\b(?:Mr|Ms|Mrs)\.?\s+[A-Z][A-Za-z'-]+(?:\s+[A-Z][A-Za-z'-]+)?"
matches = bills_actions["action"].str.findall(pattern)

pattern = r"(?i)\b(?:Mr|Ms|Mrs)\.?\s+([A-Z][A-Za-z'-]+)"
last_names = bills_actions["action"].str.findall(pattern)

matches.head(10)         # see a few lists
matches.explode().value_counts().head(20)  # most frequent titles+names

action
Mr. Engel moved         59
Mr. Pallone moved       58
Mr. Takano moved        58
Ms. Waters moved        32
Mr. Smith               28
Mr. McGovern            27
Ms. Velazquez moved     25
Mr. Roy demanded        25
Mr. Brown               24
Mr. Rouda moved         22
Ms. Kelly               21
Mr. Huffman moved       21
Mr. San Nicolas         20
Ms. Torres Small        20
Mr. Thompson            19
Ms. Norton moved        18
Ms. Jackson Lee         17
Mr. DeFazio moved       17
Mr. DeSaulnier          17
Mr. Woodall demanded    16
Name: count, dtype: int64

In [47]:
pattern = r"(?i)\b(?:Mr|Ms|Mrs)\.?\s+[A-Z][A-Za-z'-]+(?:\s+[A-Z][A-Za-z'-]+)?"
matches = bills_actions["action"].str.findall(pattern)

In [48]:
bills_actions["bill_id"] = (
    bills_actions["Congress"].astype(str) + "-" +
    bills_actions["bill_type"].astype(str) + "-" +
    bills_actions["bill_number"].astype(str)
)

In [50]:
import re
import pandas as pd

# 1) pattern and matches in a NEW COLUMN
pattern = r"(?i)\b(?:Mr|Ms|Mrs)\.?\s+[A-Z][A-Za-z'-]+(?:\s+[A-Z][A-Za-z'-]+)?"
bills_actions = bills_actions.copy()
bills_actions["persons"] = (
    bills_actions["action"]
    .astype("string").fillna("")
    .str.findall(pattern)
)

# 2) unique bill id (adjust if your key is different)
bills_actions["bill_id"] = (
    bills_actions["Congress"].astype(str) + "-" +
    bills_actions["bill_type"].astype(str) + "-" +
    bills_actions["bill_number"].astype(str)
)

# 3) explode, drop empties, de-duplicate person–bill pairs
mentions = bills_actions.explode("persons", ignore_index=True)
mentions = mentions.dropna(subset=["persons"])
person_bill = mentions.drop_duplicates(subset=["persons", "bill_id"])

# 4) counts per person and distribution
counts = (
    person_bill.groupby("persons")["bill_id"]
    .nunique()
    .sort_values(ascending=False)
    .reset_index(name="n_bills_mentioned")
)

distribution = counts["n_bills_mentioned"].value_counts().sort_index()

counts.head(20), distribution

(                 persons  n_bills_mentioned
 0        Mr. Engel moved                 59
 1      Mr. Pallone moved                 58
 2       Mr. Takano moved                 57
 3       Ms. Waters moved                 32
 4           Mr. McGovern                 25
 5    Ms. Velazquez moved                 25
 6        Mr. Rouda moved                 22
 7              Ms. Kelly                 21
 8      Mr. Huffman moved                 21
 9              Mr. Brown                 19
 10       Mr. San Nicolas                 19
 11      Ms. Torres Small                 18
 12      Ms. Norton moved                 18
 13     Mr. DeFazio moved                 17
 14  Mr. Woodall demanded                 16
 15          Mr. Thompson                 15
 16     Ms. Haaland moved                 15
 17    Mrs. Dingell moved                 15
 18       Mr. Sires moved                 15
 19     Ms. Lofgren asked                 15,
 n_bills_mentioned
 1     274
 2     113
 3      71
 4      28
 5      34
 6      17
 7      13
 8      10
 9       4
 10      2
 11      8
 12      6
 13      1
 14      5
 15      5
 16      1
 17      1
 18      2
 19      2
 21      2
 22      1
 25      2
 32      1
 57      1
 58      1
 59      1
 Name: count, dtype: int64)